baseurl: "" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "trustlix.org" # the base hostname & protocol for your site.
title: "trustlix.org"

paginate: 6 #articles per page
paginate_path: /blog/page:num #makes pagination working

#contacts
github: "https://github.com/trustlix"
stackoverflow: "http://stackoverflow.com/users/3878208/trustlix"
twitter: "https://twitter.com/trustlix"
linkedin: "https://br.linkedin.com/in/trustlix" 

#disqus comment
disqus:
    shortname: "test" #your disqus comment short name

#google analytics
google:
    tracking-id: "" #your tracking id here

gems:
  - jekyll-sitemap
  - jekyll-paginate

# This is used by feed.xml. Uncomment if you want to use it.
# description: "..."

exclude:
  - "README.md"
  - "CHANGELOG.md"
  - "Gemfile"
  - "Gemfile.lock"
  - "screenshots"

permalink: /posts/:title

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
